---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-mini-project-d840b523                  # Ingress name
  labels:
    app: spring-mini-project-d840b523
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "spring-mini-project-d840b523.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-mini-project-d840b523               # Links to Service name dynamically
                port:
                  number: 8080  # Links to service port dynamically
